services:
  postgres:
    container_name: origin-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: origin
      PGDATA: /var/lib/postgresql/data