-- Rename Ranking enum values to new naming convention
ALTER TYPE "Ranking" RENAME VALUE 'MORTAL' TO 'DISCRETO';
ALTER TYPE "Ranking" RENAME VALUE 'DESBRAVADOR' TO 'CONTINUO';
ALTER TYPE "Ranking" RENAME VALUE 'HEROI' TO 'DIFERENCIAVEL';
ALTER TYPE "Ranking" RENAME VALUE 'EPICO' TO 'NAO_LINEAR';
ALTER TYPE "Ranking" RENAME VALUE 'LENDARIO' TO 'SINGULAR';
ALTER TYPE "Ranking" RENAME VALUE 'MITICO' TO 'DIVERGENTE';
ALTER TYPE "Ranking" RENAME VALUE 'ANCESTRAL' TO 'CAOTICO';

-- Update default value on Character.ranking column
ALTER TABLE "Character" ALTER COLUMN "ranking" SET DEFAULT 'DISCRETO';
